# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'travana' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftyJSON', '5.0.0'
  pod 'Willow', '5.2.1'

  target 'travanaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'travanaUITests' do
    # Pods for testing
  end

end
